version: '3.8'

services:
  nginx:
    image: trafex/php-nginx:3.5.0
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./
        target: /var/www/html

  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
    volumes:
      - type: bind
        source: ./db_data
        target: /var/lib/postgresql/data
